/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EssaysRouteImport } from './routes/essays'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysRoute = EssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/essays': typeof EssaysRoute
  '/library': typeof LibraryRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/essays': typeof EssaysRoute
  '/library': typeof LibraryRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/essays': typeof EssaysRoute
  '/library': typeof LibraryRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/authors'
    | '/books'
    | '/essays'
    | '/library'
    | '/newsletter'
    | '/podcast'
    | '/reports'
    | '/research'
    | '/api/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/authors'
    | '/books'
    | '/essays'
    | '/library'
    | '/newsletter'
    | '/podcast'
    | '/reports'
    | '/research'
    | '/api/subscribe'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/authors'
    | '/books'
    | '/essays'
    | '/library'
    | '/newsletter'
    | '/podcast'
    | '/reports'
    | '/research'
    | '/api/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthorsRoute: typeof AuthorsRoute
  BooksRoute: typeof BooksRoute
  EssaysRoute: typeof EssaysRoute
  LibraryRoute: typeof LibraryRoute
  NewsletterRoute: typeof NewsletterRoute
  PodcastRoute: typeof PodcastRoute
  ReportsRoute: typeof ReportsRoute
  ResearchRoute: typeof ResearchRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays': {
      id: '/essays'
      path: '/essays'
      fullPath: '/essays'
      preLoaderRoute: typeof EssaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AuthorsRoute: AuthorsRoute,
  BooksRoute: BooksRoute,
  EssaysRoute: EssaysRoute,
  LibraryRoute: LibraryRoute,
  NewsletterRoute: NewsletterRoute,
  PodcastRoute: PodcastRoute,
  ReportsRoute: ReportsRoute,
  ResearchRoute: ResearchRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
